setwd("C:/Users/Sarabraj/OneDrive/Programming/R/exdata")
mydata <- read.csv("household_power_consumption.txt", header = TRUE, na.strings="?", sep=";")
mydata$Date <- as.Date(mydata$Date, format="%d/%m/%Y")
subset <- subset(mydata, subset = (Date >= "2007-02-01" & Date <= "2007-02-02"))
dateandtime <- paste(as.Date(subset$Date), subset$Time)
subset$datetime <- as.POSIXct(dateandtime)
with(subset, {
  plot(Sub_metering_1~datetime, type = "l", ylab = "Global Active Power (Kilowatts)", xlab = "")
  lines(Sub_metering_2~datetime, col = 'Red')
  lines(Sub_metering_3~datetime, col = 'Blue')
})
legend("topright", col=c("black", "red", "blue"), lty = 1, lwd = 2, 
legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.copy(png, file = "plot3.png", height = 480, width = 480)
dev.off()