setwd("C:/Users/Sarabraj/OneDrive/Programming/R/exdata")
mydata <- read.csv("household_power_consumption.txt", header = TRUE, na.strings="?", sep=";")
mydata$Date <- as.Date(mydata$Date, format="%d/%m/%Y")
subset <- subset(mydata, subset = (Date >= "2007-02-01" & Date <= "2007-02-02"))
dateandtime <- paste(as.Date(subset$Date), subset$Time)
subset$datetime <- as.POSIXct(dateandtime)
plot(subset$Global_active_power~subset$datetime, type = "l", ylab = "Global Active Power (Kilowatts)", xlab = "")
dev.copy(png, file = "plot2.png", height = 480, width = 480)
dev.off()